# GitHub Actions workflow for publishing Deno CLI as NPM package
name: NPM Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update version and create tag
        run: |
          npm version ${{ github.event.inputs.version }}
          git push origin main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get new version and set output
        id: version
        run: |
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "version=v$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "✅ Version updated to v$NEW_VERSION and tag created successfully by ${{ github.actor }}"
          echo "This will trigger the publish workflow automatically"

  build:
    runs-on: ${{ matrix.os }}
    needs: create-tag

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            output_name: fmext-linux-x64
          - target: x86_64-apple-darwin
            os: macos-latest
            output_name: fmext-macos-x64
          - target: aarch64-apple-darwin
            os: macos-latest
            output_name: fmext-macos-arm64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            output_name: fmext-windows-x64.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Build for ${{ matrix.target }}
        run: |
          mkdir -p dist
          deno compile --allow-read --target ${{ matrix.target }} --output dist/${{ matrix.output_name }} mod.ts

      - name: Set execute permission (Unix)
        if: runner.os != 'Windows'
        run: chmod +x dist/${{ matrix.output_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output_name }}
          path: dist/${{ matrix.output_name }}*

  publish:
    needs: [build, create-tag]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure npm
        run: |
          npm config delete always-auth
          npm config set registry https://registry.npmjs.org/

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-artifacts/

      - name: Organize artifacts
        run: |
          mkdir -p dist
          find dist-artifacts/ -name "fmext-*" -type f -exec cp {} dist/ \;
          chmod +x dist/fmext-* || true

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
