# GitHub Actions workflow for publishing Deno CLI as NPM package
name: NPM Publish

on:
  push:
    tags:
      - 'v*.*.*'  # タグがv1.0.0のような形式の時に実行

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            output_name: fmstat-linux-x64
          - target: x86_64-apple-darwin
            os: macos-latest
            output_name: fmstat-macos-x64
          - target: aarch64-apple-darwin
            os: macos-latest
            output_name: fmstat-macos-arm64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            output_name: fmstat-windows-x64.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Build for ${{ matrix.target }}
        run: |
          mkdir -p dist
          deno compile --allow-read --target ${{ matrix.target }} --output dist/${{ matrix.output_name }} mod.ts

      - name: Set execute permission (Unix)
        if: runner.os != 'Windows'
        run: chmod +x dist/${{ matrix.output_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output_name }}
          path: dist/${{ matrix.output_name }}*

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure npm
        run: |
          npm config delete always-auth
          npm config set registry https://registry.npmjs.org/

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-artifacts/

      - name: Organize artifacts
        run: |
          mkdir -p dist
          find dist-artifacts/ -name "fmstat-*" -type f -exec cp {} dist/ \;
          chmod +x dist/fmstat-* || true

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
